### ISSUE TITLE
Audiobooks - Add note regarding ZIP compression method 'store' for media files

### ISSUE THREAD

**Issue by larscwallin** [w3c/audiobooks#10]
The ZIP format allows individual files to specify compression algorithm. The default options are Store and Deflate. Store leaves the file uncompressed while Deflate compresses the file. 
Many ZIP libraries will compress media files such as audio and video using the Deflate algorithm. When compressed, the Deflate algorithm will affect the media files in a way that makes "seeking" into them directly from the archive, without first extracting them, impossible. The result is that you always need to start from the beginning of the stream when reading from the file, even if you want to start playback 10 seconds from the end.

I would like to suggest that we add a section to the Audiobooks spec regarding compression that recommends, or even requires media files to be 'stored' rather than 'deflated'. This would be a highly logical addition to the format since it should be optimized for streaming I think.

The drawbacks are few. As far as file size is concerned it makes little difference as most media formats already are compressed (mp4, mp3, etc.)

**Comment by llemeurfr** [comment]
A section was added to https://w3c.github.io/lpf/ which uses SHOULD. Its wording is an adaptation of the EPUB 3.2 spec.
