### ISSUE TITLE
Alalso mention alternate text equivalent along with sync narration

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/audiobooks#13]
It is really good to see that editor's draft presents sync narration as the accessible alternate of audio files.
Along with sync narration / sync media, the text equivalent like text in HTML file should also be mentioned.
Sync media is a great way to ensure accessibility to people with different kind of needs. At the same time it takes human labor to synchronize text with equivalent audio. There are some automated solutions available for English and other popular European language but not for other languages.
So, it may be more economical to generate simple text in well structured HTML.
Therefore it would be good to mention it along with sync narration.

**Comment by wareid** [comment]
I addressed this in the draft, please reopen if it's not enough.

**Comment by avneeshsingh** [comment]
In the new draft, the text equivalent html files are added to resources, which is good.
We should also ensure that these files are in reading order, just as it is done for cync narration.

for example:
	"readingOrder" : [{
		"type"	: "LinkedResource",
		"url"   : "audio/part001.wav#0",
		"encodingFormat" : "audio/vnd-wav",
		"name"  : "Chapter 1",
		"duration" : "457.931",
		"alternate" : "EquivalentText/part001.html"
	},
