### ISSUE TITLE
Define how UA should deal with erroneous audiobooks

### ISSUE THREAD

**Issue by llemeurfr** [w3c/audiobooks#24]
The question came during TPAC 2019. 

An audiobook MUST contain audio files only inside its reading order. 
But if a UA fetches an audiobook which has a non-audio file in its reading order, should it reject the audiobook or should it skip the faulty file? 

More generically, should a UA try to support erroneous audiobooks as much as possible or strictly reject them?

**Comment by llemeurfr** [comment]
relates to https://github.com/w3c/pub-manifest/issues/65

**Comment by llemeurfr** [comment]
In the case an audiobook contains non-audio files or files in an audio format the UA cannot play, we should IMO take a liberal approach and request the UA to skip the file, we a note recommending the UA to present a non-blocking message about this error. 

Note that the audio format will be inferred from the encoding format. Audiobook UAs will support a limited set of encoding formats.

**Comment by swickr** [comment]
relates to #6 also (which was closed but I haven't found the discussion that led to closing)
