### ISSUE TITLE
toc links

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#31]
In the toc section, it says that when there is supplemental content:

    the table of contents SHOULD include a link to all resources

with a pointer to the resource list, but this seems too general. If that is the case, wouldn't it have to link to any css, images, scripts, etc. to avoid warnings?

Is the intention to link to all resources in the reading order and the supplementary resources?

**Comment by mattgarrish** [comment]
I see it now says:

> the table of contents SHOULD include a link to any resources a user can interact with; and

But if this is just about supplemental content, that might be the simpler terminology, so something like: 

"the table of contents SHOULD link to all the supplemental content; and"

There's something of an impossibility here, though, in terms of ever enforcing this. I wonder if it should be a note instead of a normative statement:

"When including supplemental content, be aware that users might not have access to this content unless it is linked to from the table of contents. It is strongly advised to provide links to all content
that is not in the default reading order."

Or something like that.

**Comment by wareid** [comment]
Modified the language slightly and included the note.
