### ISSUE TITLE
fragment identifiers

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#41]
It might be necessary to say something about support for fragment identifiers - are they unsupported and stripped for audiobooks, can a user agent interpret them as it chooses, is it required to support some or all of [media fragments](https://www.w3.org/TR/media-frags/), etc.

**Comment by wareid** [comment]
I mention media-frags in one of the examples, but I'm not sure of the best place to specify it in the spec because they can be used throughout, would it be sufficient to mention just in readingOrder?

**Comment by mattgarrish** [comment]
That seems like the place where it would be most relevant to talk about, as it was suggested they could be used to specify a start position.
