### ISSUE TITLE
length not duration at resource level

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#42]
In 4.4.3 it says:

> Duration SHOULD be expressed for the entirety of the audiobook as part of the manifest, and SHOULD be present at the item level in the default reading order.

LinkedResource defines a `length` property, though, not duration.

I still find this situation weird, especially since the two properties also differ in values. No way we can standardize?

**Comment by wareid** [comment]
I think we decided it's duration for all, not length, though it was discussed (I strongly dislike the idea of two different values for the same information). Can we change linked resource to duration?

**Comment by mattgarrish** [comment]
Ya, we'll need to change pub manifest, then. Since `length` was created for audiobooks, I'm going to assume that if you changed your mind here we can just flip the property without discussion.
