### ISSUE TITLE
only audio in the reading order?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#44]
The resource list says that supplemental content must be listed in the resource list, but we don't forbid resources from being listed in both.

It would probably be good to clarify that both cases are true (i.e., must in resources; must not in reading order).

Am I right in assuming that only audio content is allowed in the reading order? The reading order definition mentions it's a progression through the audio resources but doesn't say if it's a must. If so, that might be useful to note in the reading order. We'd probably need to check this during validation of the manifest, although it seems tricky.

**Comment by wareid** [comment]
We do say in the specification that the DRO can only contain audio resources, so resource list holds everything else. Do I need to be more clear in resources that it MUST be all non-audio resources or the MUST in readingOrder is sufficient?

**Comment by mattgarrish** [comment]
I didn't spot a "must" in the reading order. There's only a descriptive sentence:

> The default reading order is a specific progression through the audio resources in the audiobook.

Without a "must", it's hard to be sure if that's actually a requirement or just a general expectation that audio books have audio. I'd make it more explicit by also adding a para like the following after the requirement for at least one audio resource:

> The default reading order MUST NOT contain non-audio resources.

If you put that in, then you really don't need to say that supplemental resources must be in the resource list, as there isn't anywhere else they could be listed. It takes away that ambiguity entirely.

**Comment by mattgarrish** [comment]
Looks good.
