### ISSUE TITLE
remove para about authored/canonical manifest

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#47]
This para after the requirements refers to the old concepts:

> These properties do not all have to be serialized in the authored manifest. Refer to each property's definition to determine whether it is required in the manifest or can be compiled into the canonical manifest from other information.

See the note we added instead here: https://w3c.github.io/pub-manifest/#manifest-requirements

I'd avoid having requirements based on the internal representation. It'll just confuse people about what they're supposed to author.

It doesn't seem like title should be required, for example, since there are alternative ways of obtaining it. That might need to be lowered to recommended unless you really don't want anyone using the fallbacks?

**Comment by mattgarrish** [comment]
This looks good, but there's a broken link because we don't include a webidl representation for audiobooks. We should probably add.

**Comment by wareid** [comment]
The `#app-internal-rep-data-model` reference? Should I expand that to `[pub-manifest]/#app-internal-rep-data-model`?

**Comment by mattgarrish** [comment]
Ya, but wondering how best to approach this. The only real difference I see at the WebIDL-level is that the default for `type` is Audiobook, as there's no keyword for recommendations.

Maybe we could just note that and point across:

> Refer to the [internal representation data models](https://www.w3.org/TR/pub-manifest/#app-internal-rep-data-model) [[pub-manifest]] for more information (the Audiobooks representation only differs in the default value for `type`).

@iherman any opinion on this?

**Comment by iherman** [comment]
> Maybe we could just note that and point across:
>
>> Refer to the internal representation data models [[pub-manifest]] for more information (the Audiobooks representation only differs in the default value for type).

Short and to the point. 👍 to that.

**Comment by mattgarrish** [comment]
Closing this, as well, as I just made the last tweak to #56.
