### ISSUE TITLE
should absence of type be audiobook?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#48]
For the generic manifest, if `type` isn't specified it gets set to CreativeWork. That'll apply here, too.

If you'd rather default to Audiobook, we can do that but it probably means moving the extension steps higher up in the pub manifest algorithm so the profile defaults get priority.

/cc @iherman

**Comment by iherman** [comment]
Not necessarily. CreativeWork is the generic type, and it is perfectly fine to _add_ Audiobook to the type. That can be done at the extension point callback as it is today...

**Comment by mattgarrish** [comment]
You could, but Audiobook is a specific type of CreativeWork, so having both is redundant when Audiobook already exposes all of the properties of CreativeWork and more.

**Comment by mattgarrish** [comment]
Also, how do you know that type wasn't authored when the general rules kick in first and add a default? Are you suggesting for audiobooks that regardless of what the author puts in, if `Audiobook` isn't specified it has to be inserted?

**Comment by iherman** [comment]
I guess this is moot in view of https://github.com/w3c/pub-manifest/pull/165 ...

**Comment by mattgarrish** [comment]
Still need to know if this is the expected behaviour, though.

@wareid, if `type` isn't set should there be a default of 'Audiobooks' like we do with CreativeWork in pub manifest?

**Comment by wareid** [comment]
Yes I think so.

**Comment by mattgarrish** [comment]
Okay, I can add back the publication types section in a slightly reduced form in the branch I'm working on if you want as part of tweaking the algorithm.

**Comment by wareid** [comment]
Works for me!

**Comment by mattgarrish** [comment]
Closing this as it is addressed in #56.
