### ISSUE TITLE
required links?

### ISSUE THREAD

**Issue by iherman** [w3c/audiobooks#49]
The standard refers to `link` as one of the recommended terms which is also tested when the manifest is checked. Why is that? Isn't the reading order and the resource list enough?

**Comment by mattgarrish** [comment]
Since you should have a PEP and it can't be in the reading order, I'm fine with only taking links out. There isn't a reason you need to have links to supplemental content in the spec.

**Comment by wareid** [comment]
Let's remove link!

**Comment by mattgarrish** [comment]
Okay, I'll update in the cleanup branch.

**Comment by mattgarrish** [comment]
Closing this as it is addressed in #56.
