### ISSUE TITLE
duration check in the reading order item

### ISSUE THREAD

**Issue by iherman** [w3c/audiobooks#55]
The current processing step 4.1 of the validation test a validation error is raised if the duration is not set for a reading order item. This does make sense, but the core text should say (e.g., in §5.5) that the item _SHOULD_ include a duration value. Currently, it is not there I believe...

**Comment by iherman** [comment]
Actually, there is more: step 3.3 which checks the presence of cover, a11y report and privacy policy; these are not listed as _SHOULD_-s in the text.

**Comment by mattgarrish** [comment]
> This does make sense, but the core text should say (e.g., in §5.5) that the item _SHOULD_ include a duration value.

Ah, right, I was thinking of the global duration check that already exists in pub manifest. But we need to also check each linkedresource to ensure it has a valid duration.

**Comment by mattgarrish** [comment]
> the presence of cover, a11y report and privacy policy; these are not listed as _SHOULD_-s in the text

I think this was done in response to #30, I believe, but that was more specifically about `resources` and `links` (I just mentioned the relations because they could be in either list, so you can never guarantee the presence of those properties).

Did you still want those three relations removed @wareid ?

**Comment by wareid** [comment]
Yes let's remove them.

**Comment by mattgarrish** [comment]
Okay, thanks, I'll remove the check from algorithm steps.

**Comment by mattgarrish** [comment]
Closing this as it is addressed in #56.
