### ISSUE TITLE
Rules on finding the ToC are not precise enough

### ISSUE THREAD

**Issue by iherman** [w3c/audiobooks#63]
Between the lines the spec suggests that finding the ToC follows these steps:

1. If the PEP is used (see #61 on this, b.t.w.) and the PEP does include a ToC (i.e., an element with `role=doc-toc`) then take this
2. Otherwise, use the manifest to locate, as part of one of the Linked Resources, a reference to the ToC (following [Pub Manifest §4.8.1.3](https://www.w3.org/TR/pub-manifest/#pub-table-of-contents) and then [Pub Manifest §C.3](https://www.w3.org/TR/pub-manifest/#app-toc-ua)). 

However, (1) is not clearly specified in the document. The document(s) today would require to add a linked resource into the manifest pointing at the PEP...

I believe that:

- just as we do with the manifest processing in [Audiobook §6](https://www.w3.org/TR/audiobooks/#audio-manifest-processing), there should be a separate section on how this profile extends the general text
- again just as in the manifest processing part there should be an 'extension point' defined in [Pub Manifest §C.3](https://www.w3.org/TR/pub-manifest/#app-toc-ua) for profiles in general.

**Comment by iherman** [comment]
See https://github.com/w3c/audiobooks/pull/66 and https://github.com/w3c/pub-manifest/pull/183 for the necessary changes.

**Comment by mattgarrish** [comment]
Closing this issue as it appears we merged the referenced pull requests to fix the problem some time back.
