### ISSUE TITLE
Should we reference a newer ISO-8601?

### ISSUE THREAD

**Issue by marisademeglio** [w3c/audiobooks#65]
I noticed that we reference [ISO-8601:2004](https://www.iso.org/standard/40874.html). It has a note under [lifecycle](https://www.iso.org/standard/40874.html#lifecycle) that it is "Now withdrawn. Revised by [ISO-8601-2019-1](https://www.iso.org/standard/70907.html) and [ISO-8601-2019-2](https://www.iso.org/standard/70908.html)". Should we reference the newer one instead? Caveat: I have no idea what the changes were.

**Comment by wareid** [comment]
As far as I can tell without scaling the paywall, we're ok in referencing 2004, but I am happy to update the reference.

**Comment by mattgarrish** [comment]
If it's been withdrawn, we should probably update the reference.

It looks like 8601:2004 becomes 8601-1:2019 per the preview, and not a lot has changed:

>The main changes compared to ISO 8601:2004 are as follows:
>
> - conversion of the content as Part 1 with the Part title “Basic rules” due to the addition of another Part 2 “Extensions” of ISO 8601;
> - replacement of the term “midnight” with “beginning of day”, disallowing the value “24” for hour;
> - update of terms and definitions:
>     - “time point” is now “time”;
>     - “local time” is now “local time of day”;
>     - added definition for “time of day” and “local time scale”;
>     - updated definitions for “standard time of day”, “local time of day” and “UTC of day” to rely on “time of day”;
>     - combined two “day” terms in different domains for consistency;
>     - change of the representation of “leap seconds”;
> - clarification of “calendar day” expressions intended to mean “calendar day of week” (etc.);
> - amendment of the recurring time interval (3.1.1.11) to provide a link to ISO 8601-2:2019 which contains in Clause 5 the “repeat rules for recurring time intervals”.

But the extension stuff in Part 2 is a mystery to me, not wanting to scale that paywall, either. From what little I found online, it's all new. Section 11 appears to deal with durations.

**Comment by mattgarrish** [comment]
This no longer appears to apply to audiobooks as the duration stuff was moved to pub-manifest.

The specref database doesn't have entries for the updated 8601 standards, so we'd have to put in a patch and/or use our local biblio file.

@iherman is it required to have the newest reference for ISO specs, or can we get away with still using the older document reference?

**Comment by iherman** [comment]
> @iherman is it required to have the newest reference for ISO specs, or can we get away with still using the older document reference?

It is better to use the latest possible reference. We can actually update [specref](https://www.specref.org), too

**Comment by iherman** [comment]
I have actually made a PR on specref: https://github.com/tobie/specref/pull/622.

For now, we should probably use our own biblio.js with the 8601-1 key; we can always remove our own version later, of specref gets updated.

**Comment by mattgarrish** [comment]
Okay, sounds good. I'll make the changes to pub-manifest.

Unfortunately, I guess that means we'll need to refresh it, too...
