### ISSUE TITLE
Typos in Media Fragments URI temporal syntax?

### ISSUE THREAD

**Issue by danielweck** [w3c/audiobooks#67]
https://w3c.github.io/audiobooks/

For example: `"url" : "audio/part001.wav#0"`
...shouldn't this be `"url" : "audio/part001.wav#t=0"`?

https://www.w3.org/TR/media-frags/#naming-time

(there are 3 separate instances, to find them search for `.wav#` in the document)

**Comment by HadrienGardeur** [comment]
This seems to be addressed in https://github.com/w3c/audiobooks/pull/69 now
