### ISSUE TITLE
identifier property: id or @id ?

### ISSUE THREAD

**Issue by danielweck** [w3c/audiobooks#79]
https://w3c.github.io/audiobooks/#audio-simple
=>
```
 "@id": "https://librivox.org/flatland-a-romance-of-many-dimensions-by-edwin-abbott-abbott/",
```

vs.

https://w3c.github.io/audiobooks/#audio-supplemental
=>
```
"id" : "https://publisher.example.com/janeeyre",
```

Which syntax is correct?

In the main specification:

https://w3c.github.io/pub-manifest/#canonical-identifier
```
"id"  : "urn:isbn:9780123456789",
```

Thank you :)

**Comment by llemeurfr** [comment]
This is definitely "id" in the spec and EXAMPLE 15 must be corrected. 

Note: parsers do not have to deal with JSON-LD aliases (i.e. @id -> id in https://www.w3.org/ns/pub-context).

**Comment by wareid** [comment]
Fixed: https://github.com/w3c/audiobooks/commit/5ff1847cec514b51d57243d7b3b23860b087d9d4

**Comment by llemeurfr** [comment]
Thanks Wendy!
