### ISSUE TITLE
Minor inconsistency in conformsTo section

### ISSUE THREAD

**Issue by marisademeglio** [w3c/audiobooks#80]
[Here](https://www.w3.org/TR/audiobooks/#audio-conformance), it says the conformsTo URL must be "https://www.w3.org/TR/audiobooks" (no trailing slash) and then in the example, it uses "https://www.w3.org/TR/audiobooks/" (with trailing slash). The [pub manifest spec](https://www.w3.org/TR/pub-manifest/#profile-conformance) uses the same example (with trailing slash).

**Comment by wareid** [comment]
Fixed! Thanks for the catch.
