### ISSUE TITLE
Note audiobooks schema in specification

### ISSUE THREAD

**Issue by mattgarrish** [w3c/audiobooks#83]
Should we find a way to include a reference to the audiobook schema in the specification?

Pub manifest currently does this in a [note in the JSON-LD processing section](https://w3c.github.io/pub-manifest/#manifest-jsonld), but we don't repeat that section for audiobooks.

Maybe add an informative "JSON Schema" appendix that basically says the same thing as pub manifest note?

**Comment by iherman** [comment]
Yes, let us add this note to the audiobook spec. It is an editorial change, no problem doing this (and possibly republish the CR as an editorial change).

**Comment by mattgarrish** [comment]
I added a slightly modified version of the note to the manifest section intro in #81 (see the diff).

Is that sufficient? Thoughts on where else it might go?

**Comment by iherman** [comment]
Looks o.k. to me as it is now. Thx.

**Comment by mattgarrish** [comment]
Closing with #81
