### ISSUE TITLE
Proposed edits to section 5.11 Accessibility

### ISSUE THREAD

**Issue by marisademeglio** [w3c/audiobooks#87]
Right now, section 5.11 makes references to the work of the [Sync Media for Publications CG](https://w3c.github.io/sync-media-pub/), and acknowledges that work has not yet been stabilized. The references include specific details such as mime type, file extension, and spec name. 

I would like to propose that we avoid referencing specifics and instead use this replacement text for Section 5.11:

"
5.11 Accessibility

This section is non-normative. 

The history of the audiobook is rooted in the world of accessibility. To make publications fully accessible, content creators should refer to the [Synchronized Multimedia for Publications Community Group](https://w3c.github.io/sync-media-pub/) regarding creating synchronized accessible content and incorporating it into an Audiobook.

Alternatively, a content creator can provide the text equivalent as HTML [html] resources in the resources.
"

Furthermore, I would delete the Editor's Note as well as Example 13 and leave Example 14.

**Comment by mattgarrish** [comment]
Maybe just remove "content creators should" to avoid an rfc keyword in the section.

If I were to really nitpick, I'd probably wonder why we need to first sentence. It doesn't seem to go anywhere.

Alternatively, maybe it could be given some small context:

> The history of the audiobook is rooted in the world of accessibility. Both purely audio publications and publications that synchronize text and audio playback have long been used to assist users with alternative reading needs and preferences.
> 
> Although this specification covers the audio playback need, text and audio synchronization is currently being developed by the Synchronized Multimedia for Publications Community Group. Refer to the work of that group for more information about creating synchronized accessible content and incorporating it into an Audiobook.
> 
> Alternatively...

Or something like that.

**Comment by marisademeglio** [comment]
I like that better. 

I would eliminate "Although this specification covers the audio playback need", because it doesn't for example allow for chunking the audio content at a meaningful sub-chapter level, e.g. phrase navigation. This is use case where an audiobook produced according to this spec needs a sync overlay to enhance its accessibility. 

So maybe just say, for the start of the 2nd para:

> An approach for accessible synchronized media in publications is currently being done by the Synchronized Multimedia for Publications Community group. Refer to the work of that group for more information about creating such content and incorporating it into an Audiobook.

What do you think?
